# Generated by Django 5.0.6 on 2024-05-23 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="ISBN",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(13)],
            ),
        ),
    ]
