# Generated by Django 5.0.6 on 2024-05-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="ISBN",
            field=models.CharField(default="DEFAULT VALUE", max_length=200),
        ),
    ]
