# Generated by Django 5.0.6 on 2024-05-23 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="created_at",
        ),
    ]
