# Generated by Django 5.0.6 on 2024-05-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventoryitem_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="ISBN",
            field=models.CharField(default="Enter ISBN here", max_length=200),
        ),
    ]
