# Generated by Django 5.0.6 on 2024-05-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_inventoryitem_isbn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("manufacturer", models.CharField(max_length=100)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
    ]
