# Generated by Django 5.0.6 on 2024-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="threshold",
            field=models.IntegerField(default=10),
        ),
    ]
