# Generated by Django 5.0.6 on 2024-05-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
