# Generated by Django 5.0.6 on 2024-05-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_description'),
        ('inventory', '0005_alter_order_status'),
    ]

    operations = [
    ]
