# Generated by Django 5.0.6 on 2024-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_inventoryitem_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="threshold",
            field=models.IntegerField(default=1),
        ),
    ]
