# Generated by Django 5.0.6 on 2024-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_inventoryitem_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="reordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="ISBN",
            field=models.CharField(default="", max_length=200),
        ),
    ]
